### ISSUE TITLE
Rain and Snow decimal places in hourly not always consistent

### ISSUE THREAD

**Issue by sanders41** [sanders41/weather-command#152]
The format of the rain and snow amounts in the hourly forecast are not consistent. This should be made consistent because in some cases it looks weird. 2 decimal places seems appropriate (at least for imperial format, i.e. inches).

![Screenshot from 2022-03-19 08-43-41](https://user-images.githubusercontent.com/25045024/159121638-d3703c40-8f90-44e7-8d89-f60c0bf59b9a.png)

I think at least part of the problem is [here](https://github.com/sanders41/weather-command/blob/1b9eab5599651d7477a50db504568c6f630e0725/weather_command/_builder.py#L352).

**Comment by IanWorley** [comment]
I will take this issue.

**Comment by sanders41** [comment]
Thanks @IanWorley . Let me know if you have any questions.

**Comment by IanWorley** [comment]
Hey is there anyway for me to test my fix.

**Comment by sanders41** [comment]
Closed via #159
